##########################################################################
#
# Configuration for welcome - https://github.com/behaviorbot/welcome
#
##########################################################################

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
  Congrats on merging your first pull request! We here at behaviorbot are proud of you!
  Thank you very much for your contribution!

  ## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

  ### 1. Join Wechaty Organization

  > Please visit https://github.com/wechaty to accept the invitation.

  We have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

  ### 2. Update Your Wechaty Contributor Profile

  1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
  1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

  ### 3. Join The Contributor Only WeChat Room

  We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

  Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

  Cheers!

